baseURL = "https://kitanob.github.io/kitanoLab/"
languageCode = "fr-fr"
title = "KitanoB"
theme = "mini"
features = ["fast", "minimalist", "responsive"]
licence = "MIT"

[params]
  author = "Kitano Bjorgssen"
  bio = "Software Engineer"
  enableRSS = true
  enableComments = true
  description = "Mon parcours dans la computer science"
  keywords = "blog, tech, computer, computer science, algorithm, developer"
  colorScheme = "auto"
  showBorder = false
  mainSections = ["post"]
  showFooter = false
  showViewCounter = true
  hiddenPostSummaryInHomePage = true
  customCSS = ["/kitanoLab/css/list.css"]

[taxonomies]
  tag = "tags"
